services:
  app:
    build: .
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    restart: always
    environment:
      - PORT=${PORT}
      - DB_TYPE=${DB_TYPE}
      - DB_URI=${DB_URI}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_SECURE=${MAIL_SECURE}
      - MAIL_USER=${MAIL_USER}
      - MAIL_PASS=${MAIL_PASS}
      - MAIL_FROM_NAME=${MAIL_FROM_NAME}
      - MAIL_FROM_EMAIL=${MAIL_FROM_EMAIL}
      - MAIL_TLS_REJECT_UNAUTHORIZED=${MAIL_TLS_REJECT_UNAUTHORIZED}
      - MAIL_TLS_ENABLED=${MAIL_TLS_ENABLED}
    depends_on:
      - mongodb
      # - postgres
      # - mysql

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  # postgres:
  #   image: postgres:latest
  #   environment:
  #     - POSTGRES_USER=admin
  #     - POSTGRES_PASSWORD=password
  #     - POSTGRES_DB=mail_service_db
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

  # mysql:
  #   image: mysql:latest
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=password
  #     - MYSQL_DATABASE=mail_service_db
  #     - MYSQL_USER=admin
  #     - MYSQL_PASSWORD=password
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - mysql_data:/var/lib/mysql

volumes:
  mongodb_data:
  # postgres_data:
  # mysql_data:
